level2 = { obstacles = { ground = { name = "ground",
                                    y_top = 70,
                                    y_bottom = 96,
                                    x_left = 0,
                                    x_right = 150,
                                    active = true},
                         leftside = { name = "leftside",
                                  y_top = 0,
                                  y_bottom = 96,
                                  x_left = -10,
                                  x_right = 0,
                                  active = true },
                         rightside = { name = "rightside",
                                  y_top = 0,
                                  y_bottom = 96,
                                  x_left = 150,
                                  x_right = 160,
                                  active = true },
                         rightdoor = { name = "rightdoor",
                                       y_top = 0,
                                       y_bottom = 96,
                                       x_left = 108,
                                       x_right = 110,
                                       active = true },
                         level_2_warp = { name = "level_2_warp",
                                          y_top = 0,
                                          y_bottom = 96,
                                          x_left = 135,
                                          x_right = 150,
                                          active = true,
                                          warpzone = true,
                                          warp = "level2" } },
           fgimage = { image = 0,
                       filename = "Level1/lv1housebackground.png",
                       x_loc = 0,
                       y_loc = 0 },
           overlays = { partitions = { name = "partitions",
                                       image = 0,
                                       filename = "Level1/lv1housepartitions.png",
                                       img_x_loc = 0,
                                       img_y_loc = 0,
                                       fade = false,
                                       z = 2
                                     },
                        rightdoor = { name = "rightdoor",
                                      image = 0,
                                      filename = "Level1/lv1rightdoor.png",
                                      img_x_loc = 0,
                                      img_y_loc = 0,
                                      x_loc = 108,
                                      y_loc = 50,
                                      width = 2,
                                      height = 19,
                                      fade = false,
                                      faderange = 12,
                                      z = 1
                                     },
                        housefront = { name = "housefront",
                                       image = 0,
                                       filename = "Level1/lv1housefg.png",
                                       img_x_loc = 0,
                                       img_y_loc = 0,
                                       x_loc = 22,
                                       y_loc = 42,
                                       width = 87,
                                       height = 29,
                                       fade = true,
                                       faderange = 7.5,
                                       z = 3
                                     }
                         },
           props = { lit_interior = { name = "lit_interior",
                                      animated = false,
                                      image = 0,
                                      filename = "Level1/lv1litinterior.png",
                                      x_loc = 0,
                                      y_loc = 0,
                                      lit_up = true,
                                      z = 1 },
                     lining = {       name = "lining",
                                      animated = false,
                                      image = 0,
                                      filename = "Level1/lv1houselining.png",
                                      x_loc = 0,
                                      y_loc = 0,
                                      lit_up = false,
                                      z = 2 },
                     skirtingboard = { name = "skirtingboard",
                                       animated = false,
                                       image = 0,
                                       filename = "Level1/lv1skirtingboard.png",
                                       x_loc = 0,
                                       y_loc = 0,
                                       lit_up = true,
                                       z = 3 },
                     grandmother = { name = "grandmother",
                                     animated = true,
                                     animations = { idle = { name = "idle", currentFrame = 1, folder = "Props/Granny/Idle", frames = {} },
                                                    intense = { name = "intense", currentFrame = 1, folder = "Props/Granny/Intense", frames = {} },
                                                    panic = { name = "panic", currentFrame = 1, folder = "Props/Granny/PANIC", frames = {} } },
                                     x_loc = 62,
                                     y_loc = 50,
                                     lit_up = true,
                                     timeSinceLastFrame = 0,
                                     frameDelayms = 160,
                                     curAnim = nil },
                     cat = { name = "cat",
                             animated = true,
                             animations = { idle = { name = "idle", currentFrame = 1, folder = "Props/Cat/Idle", frames = {} },
                                            intense = { name = "intense", currentFrame = 1, folder = "Props/Cat/Intense", frames = {} },
                                            panic = { name = "panic", currentFrame = 1, folder = "Props/Cat/PANIC", frames = {} } },
                             x_loc = 32,
                             y_loc = 50,
                             lit_up = true,
                             timeSinceLastFrame = 0,
                             frameDelayms = 120,
                             curAnim = nil },
                     wallclock = { name = "clock",
                                   animated = true,
                                   animations = { tick = { name = "tick", currentFrame = 1, folder = "Props/Clock", frames = {} } },
                                   x_loc = 50,
                                   y_loc = 48,
                                   lit_up = true,
                                   timeSinceLastFrame = 0,
                                   frameDelayms = 2000,
                                   curAnim = nil } },
           lights = { middle_room = { image_on = 0,
                                     image_off = 0,
                                     filename_on = "Props/Light.png",
                                     filename_off = "Props/Light_broken.png",
                                     x_loc = 61,
                                     y_loc = 42,
                                     width = 3,
                                     height = 10,
                                     lsource_x = 2,
                                     lsource_y = 9,
                                     intensity = 6,
                                     lit = false } },
           timetaken = 0,
           panictime = 15,
           status = "calm",
           nextlevel = false }